### PR TITLE
Fix account creation on windows machines

### PR DESCRIPTION
**Pull request by Almamu**
Signed-off-by: Alexis Maiquez Murcia <almamu@almamu.com>

### CODE REVIEW

**Review by jdhirst — COMMENTED** [review]
@Almamu Oh that one is interesting, everything works fine in gcc using llu as well?

**Comment by Almamu** [comment]
I have not been able to test it myself, but thats a good point. I do remember having a define that changed based on the platform for these kind of formats. I64d and I64u I think they were.

**Comment by jdhirst** [comment]
I'll test it in gcc as-is and let you know the results 🙂

**Comment by jdhirst** [comment]
Confirmed this works fine on Linux systems. Merging :slightly_smiling_face:

**Comment by Almamu** [comment]
Nice! Now this is a problem almost everywhere in the server 😅 The biggest offender I'd say is timestamps as these are always saved as bigint and long long... I'll create an issue so we can keep track of this...

**Pull request merged**
