### PR TITLE
Vanilla Character Attributes and Skills reset

### PR DESCRIPTION
**Pull request by triple111**
This PR aligns the character attributes and starting skills with vanilla Crucible values to create a more accurate and vanilla experience. I used historical sources to find the starting values for skills, attributes, and ISK. All changes were non-destructive to allow for reversion. There are 2 new database migrations and changes to several server classes and eve-server.xml. 

A new character will now start with:
20 Perception
19 Charisma
20 Intelligence
20 Memory
20 Willpower

~60K SP
5,000 ISK

Reference: Eve University "Starting Skills" of 23 March 2013 
[https://wiki.eveuniversity.org/index.php?title=Starting_skills&direction=next&oldid=13906](url)

I am investigating the difference between the quoted 56,489 SP value and the resulting value due to these changes.

## Summary by Sourcery

This pull request updates character attributes and starting skills to match vanilla Crucible values. It includes new database migrations and modifications to server classes to support these changes. The changes are non-destructive, allowing for easy reversion if needed.

- **New Features**:
    - Introduced new character attributes and starting skills aligned with vanilla Crucible values.
- **Enhancements**:
    - Replaced outdated character attribute retrieval methods with new methods using base attributes.
    - Updated database schema to remove old attributes from chrAncestries and chrBloodlines, and added them to chrAttributes as baseAttributes.

### CODE REVIEW

**Comment by jdhirst** [comment]
@triple111 Thanks for the contribution! I looked over everything and it all looks good to me and brings us closer to that vanilla experience. 

Just a couple of things before I merge this:
1. Could you please remove the commented code sections however? I know the codebase currently has a lot of those, however it will make things easier to read and understand by cleaning them up.
2. Update that error message that references `attributeID`

**Comment by jdhirst** [comment]
To fix the workflow failure, can you please `git fetch --all; git cherry-pick f97c462900c164496321ab115927071ed44bc464`? 
This will fix the workflow bug in your branch so it can be built properly.

**Comment by triple111** [comment]
@jdhirst The requested changes are included in the latest commit. I did however have an error with the workflow failure command you requested:

`git fetch --all; git cherry-pick f97c462900c164496321ab115927071ed44bc464
Fetching origin
fatal: bad object f97c462900c164496321ab115927071ed44bc464
`

**Comment by jdhirst** [comment]
I got this to build so will merge it, the CI pipeline should work for new branches now.

**Pull request merged**
