### PR TITLE
Implement LP Wallet & LP Mission Rewards

### PR DESCRIPTION
**Pull request by beelitzs**
Implementation of the loyalty point system.
- Create DB Table to Store LP
- Create database methods to interface with DB
- Create public methods for Adding & Calculating LP
- Update client handlers to display LP balances in Journal and in LP Store
- Create event call packet to tell client when to fetch for an update and display blink effect

Notes:
- BaseLP is not exactly right, LPService.cpp:72-75 is just a quick hack to provide functionality for testing. From what I've gathered from researching this should be a dynamic system based on mission history.
- The LPStore itself isn't implemented yet but this part at least provides the prerequisites for it.

### CODE REVIEW

**Comment by Almamu** [comment]
Can one of the admins verify this patch?

**Comment by jdhirst** [comment]
Nice work @beelitzs! It looks good to me. How are loyalty points obtained currently in-game? I'm thinking, maybe we should add something to the admin commands which gives the player x amount of LP. This would be good for testing IMO.

**Comment by jdhirst** [comment]
!oktotest

**Comment by beelitzs** [comment]
@jdhirst I've updated mission offers so that you can gain LP by doing missions from agents which is how I was doing initial testing.
An admin command isn't a bad idea to add though, ill see if I can add one, should be straightforward enough.

**Comment by jdhirst** [comment]
!oktotest

**Comment by jdhirst** [comment]
@beelitzs thanks for the contribution! 😁 Merging to staging~

**Pull request merged**
