### PR TITLE
fixing both tractor beam and persistant jetcan

### PR DESCRIPTION
**Pull request by idolord**
ShipService : after populating the jetcan with items set it to unachored.
Container : implemented swich case to determine if container should be destroyer whene empty.

### CODE REVIEW

**Comment by Almamu** [comment]
Can one of the admins verify this patch?

**Comment by jdhirst** [comment]
!oktotest

**Comment by jdhirst** [comment]
I really like the simple implementation here, should do exactly what we need it to do to fix #196 

Since it just calls Delete(), I suspect no explosion animation/effect is played. Is this the case @idolord?

**Comment by idolord** [comment]
No, no animation yet I might have to dig a bit more to get the method I need to call to make it literaly "explode". If anyone have a clue ...

**Comment by jdhirst** [comment]
I checked around for a bit but couldn't find something trivial, it'll likely require a new item in DestinyManager to send the effect. As such, lets just merge this for now and that addition can come in another PR

**Comment by idolord** [comment]
I will but won't be able to before 19h GMT...
Le mer. 23 mars 2022 à 11:35, James Hirst ***@***.***> a
écrit :

**Comment by jdhirst** [comment]
Closing as obseleted by #201

**Pull request closed without merging**
