### PR TITLE
Port Staging branch to Windows

### PR DESCRIPTION
**Pull request by Pursche**
Replace pthread based threading with std::thread in Threading.h/cpp
Replace FD based non-blocking IO with platform agnostic std::thread based non-blocking IO in ConsoleCommands.return
Replace Linux-specific traceStack functionality with platform agnostic CallStack library
Add a StackAllocator
Add a per-tick StackAllocator for temporary allocations
Fix various template related forward declaration issues that only showed up on msvc

### CODE REVIEW

**Comment by jdhirst** [comment]
@Pursche do you mind making codefactor happy? 😉

**Comment by Pursche** [comment]
@jdhirst There you go!

**Comment by jdhirst** [comment]
Awesome, thanks!

!oktotest

**Comment by jdhirst** [comment]
Looks good to me, merging with staging

@Pursche Thanks for the contribution!! :)

**Pull request merged**
