### PR TITLE
Updates to mining logic

### PR DESCRIPTION
**Pull request by TheOneJohiah**
Can now activate miners when target storage hold lacks space to add a full cycle
Overflow ore will be dumped if the target storage hold lacks the space to carry it all

Previously, a miner could not be activated if the total module cycle m3 was larger than remaining space.

Tested with a bantam and two miner Is, in various configurations of auto canceling, hand canceling, etc.

Unsure if the lost ore is still deleted from the asteroid?

### CODE REVIEW

**Comment by HeiressOfTheDark** [comment]
> Is that how it works in live? I honestly have no idea :D

I believe so lol? I don't have much of an idea either myself but judging by conversations had in discord that's how it's supposed to be

**Comment by TheOneJohiah** [comment]
> > Is that how it works in live? I honestly have no idea :D
> 
> I believe so lol? I don't have much of an idea either myself but judging by conversations had in discord that's how it's supposed to be

It's definitely closer to stock behavior, I'm unsure if stock allows activating the module if your cargo is *completely* full unfortunately, can't remember. But the rest of it should be correct.

**Comment by HeiressOfTheDark** [comment]
> > > Is that how it works in live? I honestly have no idea :D
> > 
> > 
> > I believe so lol? I don't have much of an idea either myself but judging by conversations had in discord that's how it's supposed to be
> 
> It's definitely closer to stock behavior, I'm unsure if stock allows activating the module if your cargo is _completely_ full unfortunately, can't remember. But the rest of it should be correct.

Better than what we have in any case

**Comment by VizanArkonin** [comment]
Live mechanic will allow you to start a cycle - it will yield nothing once it's done, throw a notification and then deactivate. I believe that "can't start" behavior was a plug we put in until the entire system gets polished...like it does now :P

**Comment by jdhirst** [comment]
In that case, can we add the notification to this change? Once that's done I think we can merge this

**Comment by TheOneJohiah** [comment]
What notification am I missing? It does say "Your miner deactivates as it couldn't add Veldspar to the cargo hold."
I assume that's... the wrong one, or something?

**Comment by jdhirst** [comment]
Ah okay, didn't see that. Looks good to go!

**Pull request merged**
